#!/bin/bash
#SBATCH -J ForJobsOneNode      
#SBATCH -o test.o.txt 
#SBATCH -e test.e.txt 
#SBATCH -p normal   
#SBATCH -N 1       
#SBATCH -n 16
#SBATCH -t 01:30:00 
# The next line is required if the user has more than one project
#SBATCH -A XXX

module load gromacs/5.0.1

for i in `seq 0 3`
do
mkdir -p $i
cd $i
mdrun -nt 4 -s ../topol.tpr -deffnm test-gromacs-${i}  > test-stampede_${i}.log 2>&1 &
cd ../
done

wait
