#!/bin/bash
# the queue to be used
#PBS -q normal
# INSERT HERE YOUR PROJECT ALLOCATION
#PBS -A XXX
# number of nodes and number of processors per node requested
#PBS -l nodes=1:ppn=16:native
# requested Wall-clock time.
#PBS -l walltime=00:30:00
# name of the standard out file to be "output-file".
#PBS -o myoutput
#PBS -e myerror
# name of the job
#PBS -N example
#PBS -V

cd /oasis/scratch/$USER/$PBS_JOBID
cp /home/$USER/Xsede_Brandeis/Gordon/Test-Gromacs/* .

module purge 
module load gnubase/1.0
module load gromacs/5.0
module list 
echo "starting the run"
date 
mpirun -np 16 -hostfile $PBS_NODEFILE  `which mdrun_mpi` -s topol.tpr -deffnm test_gromacs  > test-gordon.log 2>&1 

echo "run finished " 


